---
title: "Share of Second Votes"
author: "Luke D. Fischer"
format: html
editor: visual
theme: journal
toc: TRUE
---

```{r}
#| echo: false
#| warning: false

library(readxl)
library(tidyverse)
library(ggplot2)
library(gganimate)
library(ggrepel)
library(patchwork)
library(gifski)

# Preliminary Data Wrangling

data <- read_xlsx("zweitstimmen.xlsx")

data <- data |> 
  select(!SSW)

data <- data |> 
  pivot_longer(
    cols = !Jahr, 
    names_to = "Partei", 
    values_to= "Share"
  )
```

## Second Vote Share Per Party over Time

```{r}
#| echo: false
#| warning: false
#| message: false

data <- data |> 
  mutate(Jahr = as.character(Jahr)) |> 
  mutate(Jahr = parse_date(Jahr, format = "%Y")) |> 
  mutate(Partei = factor(Partei, levels = c("CDU/CSU", "SPD", "FDP", "Bündnis 90/Die Grünen", "Die Linke. PDS", "AfD", "Sonstige")))


p_general <- data |> 
  ggplot(aes(
    x = Jahr, 
    y = Share, 
    color = Partei, 
    group = Partei)) + 
  geom_line(size = 0.7) + 
  geom_hline(aes(yintercept = 5), alpha = 0.3, linetype = "dotted") +
  scale_x_date(
    breaks = unique(data$Jahr), 
    date_labels = "%y")+
  scale_y_continuous(
    breaks = seq(0,55,5)
  ) +
  labs(y = "Zweitstimmenanteil") +
  scale_color_manual(values = c("black", "#E3000F", "#FFDE21", "#1AA037", "purple", "#0489DB", "gray")) +
  theme_classic() +
  transition_reveal(Jahr)

invisible(p_general) 

animation <- animate(p_general, renderer = gifski_renderer(), 
                     height = 5, 
                     width = 8, 
                     units = "in", 
                     res = 300)

animation
```

## CDU

```{r}
#| echo: false
#| warning: false
#| message: false

data <- data |> 
  mutate(CDU = if_else(Partei == "CDU/CSU", Share, NA))

data <- data |> 
  mutate(nicht_CDU = if_else(Partei != "CDU/CSU", Share, NA)) 

data <- data |> 
  mutate(CDU_sum = if_else(CDU == max(CDU, na.rm = TRUE) | CDU == min(CDU, na.rm = TRUE) | Jahr == as.Date("2025-01-01"), CDU, NA)) 



p_CDU <- data |> 
  ggplot(aes(
    x = Jahr, 
    y = CDU, 
    color = Partei)) + 
  geom_line(size = 0.7) + 
  geom_line(aes(y = nicht_CDU), 
            alpha = 0.1) +
  scale_color_manual(values = 
                       c("black", "#E3000F", "#FFDE21", "#1AA037", "purple", "#0489DB", "gray")) +
  annotate(
    "segment",
    x = as.Date("2025-01-01"),
    y = 0,
    yend = 28.6, 
    color = "black", 
    linetype = 2
  ) +
  annotate(
    "segment",
    x = as.Date("2021-01-01"),
    y = 0,
    yend = 24.1, 
    color = "black", 
    linetype = 2
  )+
  annotate(
    "segment",
    x = as.Date("1957-01-01"),
    y = 0,
    yend = 50.2, 
    color = "black", 
    linetype = 2
  )+
  geom_point(aes(y = CDU_sum),
             size = 2, 
             show.legend = FALSE) +
  scale_x_date(
    breaks = unique(data$Jahr), 
    date_labels = "'%y", 
    expand = c(0,0), 
    limits= c(as.Date("1949-01-01"), as.Date("2026-01-01"))) + 
  scale_y_continuous(expand = c(0, 0), 
                     breaks = c(data$CDU_sum, 50.2), 
                     limits = c(0, 52)) + 
  labs(y = "") + 
  theme_classic() +
  theme(axis.text.y = element_text(size=9))

invisible(p_CDU)
```

```{r}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 8
#| fig-height: 5
#| fig-dpi: 300

p_CDU
```
